# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text=b'Portfolio image', upload_to=b'portfolio/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
