# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaerd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_short', models.CharField(max_length=200)),
                ('title_long', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
