# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmaerd', '0002_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='Question',
        ),
    ]
