# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaerd', '0003_auto_20180412_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text=b'Service image', upload_to=b'services/')),
                ('text', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
