# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_pl', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(help_text=b'Portfolio image', upload_to=b'portfolio/')),
                ('text', models.CharField(max_length=200)),
                ('text_en', models.CharField(max_length=200, null=True)),
                ('text_ru', models.CharField(max_length=200, null=True)),
                ('text_pl', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_short', models.CharField(max_length=200)),
                ('title_short_en', models.CharField(max_length=200, null=True)),
                ('title_short_ru', models.CharField(max_length=200, null=True)),
                ('title_short_pl', models.CharField(max_length=200, null=True)),
                ('title_long', models.CharField(max_length=200)),
                ('title_long_en', models.CharField(max_length=200, null=True)),
                ('title_long_ru', models.CharField(max_length=200, null=True)),
                ('title_long_pl', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(max_length=1000)),
                ('text_en', models.TextField(max_length=1000, null=True)),
                ('text_ru', models.TextField(max_length=1000, null=True)),
                ('text_pl', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_pl', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(help_text=b'Service image', upload_to=b'services/')),
                ('text', models.TextField(max_length=500)),
                ('text_en', models.TextField(max_length=500, null=True)),
                ('text_ru', models.TextField(max_length=500, null=True)),
                ('text_pl', models.TextField(max_length=500, null=True)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
